<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="DemandedSpeedCalculator" Id="{38457ad0-6fb8-4aa3-a566-b0aa09b9588e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM DemandedSpeedCalculator
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="DemandedSpeedCalculator">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>